name: portofolio_web
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  fl_chart: ^0.67.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_charts: ^0.5.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  responsive_builder: ^0.7.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/project_3.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Robot.ttf
